remote_theme: daviddarnes/alembic

title: Keshav Bhupathy Vignesh
description: Developer. Designer. Python. ROS
logo: /images/logo_dark.png
url: https://www.keshavvignesh.com
permalink: /blog/:title/

paginate: 5
paginate_path: /blog/:num
# Site navigation
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Search
  url: /search/
- title: CV
  url: /CV/J_Keshav_Bhupathy_Vignesh_Resume.pdf

navigation_footer:
- title: Credits
  url : /credits
  
social_links:
  email: mailto:jkeshav.bvignesh@gmail.com
  Twitter: https://twitter.com/Keshav_Vignesh
  LinkedIn: https://www.linkedin.com/in/jkeshav-bvignesh
  GitHub: https://github.com/jkeshav-bvignesh
  facebook: https://www.facebook.com/people/Keshav-Vignesh/100005469136863

plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/favicon-16x16.png'
  32: '/assets/logos/favicon-32x32.png'
  96: '/assets/logos/favicon-32x32.png'
  120: '/assets/logos/favicon-32x32.png'
  144: '/assets/logos/favicon-32x32.png'
  180: '/assets/logos/favicon-32x32.png'
  192: '/assets/logos/android-chrome-192x192.png'
  512: '/assets/logos/android-chrome-512x512.png'

google_analytics: 'G-0YJJ8P7J97'
