remote_theme: daviddarnes/alembic

title: Keshav Bhupathy Vignesh
description: Developer. Designer. Python. ROS
logo: /images/logo_dark.png
url: https://www.keshavvignesh.com
permalink: /blog/:title/

# Disqus Comments
disqus: keshavvignesh

# Pagination
paginate: 5
paginate_path: /blog/:num

jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: jkeshavbvignesh # jekyll-seo-tag > Owners twitter username
author: keshavvignesh # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: J Keshav Bhupathy Vignesh # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/jkeshavbvignesh
    - https://www.facebook.com/people/Keshav-Vignesh/100005469136863
    - https://www.linkedin.com/in/jkeshav-bvignesh
    - https://github.com/jkeshav-bvignesh
email: "jkeshav.bvignesh@gmail.com"

# Site navigation
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Search
  url: /search/

navigation_footer:
- title: Credits
  url : /credits
  
social_links:
  email: mailto:jkeshav.bvignesh@gmail.com
  Twitter: https://twitter.com/jkeshavbvignesh
  LinkedIn: https://www.linkedin.com/in/jkeshav-bvignesh
  GitHub: https://github.com/jkeshav-bvignesh
  facebook: https://www.facebook.com/people/Keshav-Vignesh/100005469136863
  RSS: /feed.xml

plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/favicon-16x16.png'
  32: '/assets/logos/favicon-32x32.png'
  96: '/assets/logos/favicon-32x32.png'
  120: '/assets/logos/favicon-32x32.png'
  144: '/assets/logos/favicon-32x32.png'
  180: '/assets/logos/favicon-32x32.png'
  192: '/assets/logos/android-chrome-192x192.png'
  512: '/assets/logos/android-chrome-512x512.png'
