#theme: alembic-jekyll-theme

remote_theme: daviddarnes/alembic

title: Keshav Bhupathy Vignesh
description: Developer. Designer. Python. ROS
logo: /images/logo.png
url: https://www.keshavvignesh.com
permalink: /:title/

paginate: 3 
paginate_path: /blog/:num
# Site navigation
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Search
  url: /search/
- title: CV
  url: /CV/J_Keshav_Bhupathy_Vignesh_Resume.pdf

navigation_footer:
- title: Credits
  url : /credits
  
social_links:
  email: mailto:jkeshav.bvignesh@gmail.com
  Twitter: https://twitter.com/Keshav_Vignesh
  LinkedIn: https://www.linkedin.com/in/jkeshav-bvignesh
  GitHub: https://github.com/jkeshav-bvignesh
  facebook: https://www.facebook.com/people/Keshav-Vignesh/100005469136863
  Instagram: https://www.instagram.com/keshavvignesh/

plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme
