theme: alembic-jekyll-theme

title: Keshav's Blog
description: A short description of your site's purpose
logo: https://images.unsplash.com/photo-1556195332-95503f664ced?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=676&q=80

permalink: /:title/

paginate: 3 
paginate_path: /:num
# Site navigation
navigation_header:
- title: Home
  url: /
- title: Categories
  url: /categories/
- title: Search
  url: /search/
- title: About
  url: /About

navigation_footer:
- title: Keshav Bhupathy Vignesh
  url: http://www.keshavvignesh.com
social_links:
  Twitter: https://twitter.com/Keshav_Vignesh
  LinkedIn: https://www.linkedin.com/in/jkeshav-bvignesh
  GitHub: https://github.com/jkeshav-bvignesh
  link: https://www.keshavvignesh.com
